### ISSUE TITLE
no armv7 support for MiP framework

### ISSUE THREAD

**Issue by samyusk** [WowWeeLabs/MiP-iOS-SDK#10]
Hi,

Seems only Miposaur SDK framework is updated with including armv7, but MiP SDK framework still doesn't have armv7.

Thanks
Sam

**Comment by ffchan** [comment]
Hi Sam

MiP SDK framework updated. Please try again.

Thanks
David Chan

**Comment by samyusk** [comment]
Hi David,

Thanks
Sam
