### ISSUE TITLE
MipSampleProject Error

### ISSUE THREAD

**Issue by rhumbertgz** [WowWeeLabs/MiP-iOS-SDK#11]
Hi, I´m  a beginner in iOS and trying to run the MipSampleProject , but I get this error:

I´m using Mac OS 10.10.5 (14F1605)

Thanks in advance,
Humberto

ld: warning: ignoring file /Users/XXXXXX/Documents/XCode Projects/MiP-iOS-SDK/WowWeeMiPSDK.framework/WowWeeMiPSDK, missing required architecture x86_64 in file /Users/Humberto/Documents/XCode Projects/MiP-iOS-SDK/WowWeeMiPSDK.framework/WowWeeMiPSDK (2 slices)
Undefined symbols for architecture x86_64:
  "_MipRobotFinderNotificationID", referenced from:
      -[ViewController addNotificationObservers] in ViewController.o
      -[ViewController removeNotificationObservers] in ViewController.o
  "_OBJC_CLASS_$_MipRobotFinder", referenced from:
      objc-class-ref in DriveViewController.o
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_MipRobotSound", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by guycalledian** [comment]
rhumbertgz,

It sounds like you are running on the simulator, at the moment the SDK only compiles on the device.

**Comment by rhumbertgz** [comment]
guycalledian, many thanks :)

Yesterday I was playing with my MiP but using Android SDK, now I can do the same with iOS :)

Thanks again!!!!!

Humberto
