### ISSUE TITLE
a crash is found in turbo dave SDK

### ISSUE THREAD

**Issue by samyusk** [WowWeeLabs/MiP-iOS-SDK#15]
Hi, we've been waiting for Turbo Dave SDK to integrate to our app and we're excited that MiP SDK has just been updated with Turbo Dave support. While we're testing it, we find one crash inside the SDK after enabling the radar . The details are given as follows

[1] Modify the MiP SDK sample project to call [self.mip setMipRadarMode:kMipRadarMode_On]; when "Change LED Color" button is clicked like below
- (IBAction)changeChestRGBPressed:(id)sender {
	[self.mip setMipRadarMode:kMipRadarMode_On];
}

[2] run MiP SDK sample project to connect to original MiP

[3] Click "Change LED Color" button.

[4] exception is reported by the Xcode as below

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 0]'
*** First throw call stack:
(0x18ae82fe0 0x1898e4538 0x18ad61200 0x100298af8 0x100296b7c 0x18ae1d5f4 0x18ae1cd08 0x18ae1ca84 0x18ae8b7a8 0x18ad6095c 0x18b872930 0x1002b8814 0x1002c2a08 0x100159a50 0x100159a10 0x10015eb78 0x18ae310c8 0x18ae2ece4 0x18ad5eda4 0x18c7c8074 0x191012058 0x1000ef174 0x189d6d59c)
libc++abi.dylib: terminating with uncaught exception of type NSException

The backtrace shown by the Xcode is given below. Looks like the crash occurs when executing [__NSArrayM objectAtIndex:] inside -[MipRobot handleReceivedMipCommand:] 

<img width="582" alt="screen shot 2017-06-29 at 6 15 56 pm" src="https://user-images.githubusercontent.com/14962965/27684447-a2b598f4-5cfc-11e7-9b83-6bdd2e1949d1.png">

Please feel free to let me know if more info. is needed for this issue. 
Thanks a lot.

Sam

**Comment by alexlamytt** [comment]
Thank you for your report!

Fixed in the latest commit 3b2d46a
