### ISSUE TITLE
Displaying battery level on wowwee Mip

### ISSUE THREAD

**Issue by mikevanmeter** [WowWeeLabs/MiP-iOS-SDK#6]
Beginner programmer here needs some direction on displaying battery level on Mip Robot.  Getting double zeros presently.

**Comment by hongkongkiwi** [comment]
Hi @mikevanmeter , please take a look at this protocol:

https://github.com/WowWeeLabs/MiP-BLE-Protocol/blob/master/MiP-Protocol.md

The status function should show the battery level, you can see the values in Byte1.

**Comment by mikevanmeter** [comment]
Thanks Andy,  That get me started in the right direction.  Still struggling with displaying the voltage in a label field.  I learn something new each day.
