### ISSUE TITLE
MiP robot connection issue in iOS9

### ISSUE THREAD

**Issue by samyusk** [WowWeeLabs/MiP-iOS-SDK#8]
Hi,

In iOS9.1, we've found that the MiP robot can't be scanned and connected again for the following scenario

1. power on MiP robot
2. use [[MipRobotFinder sharedInstance] clearFoundMipList] and  [[MipRobotFinder sharedInstance] scanForMips] to scan the robot, and then [MipRobot connect] to connect to a MiP robot
3. wait unit the MipDeviceReady: is called properly
4. power off MiP robot
5. MipDeviceFailedToConnect:error: is called <--- strange
6. power on MiP robot again
7. use  [[MipRobotFinder sharedInstance] clearFoundMipList] and [[MipRobotFinder sharedInstance] scanForMips] to scan the MiP again, but no MiP can be scanned.

Before MipDeviceFailedToConnect:error: in step 5 is called, the log "YMSCBCentralManager didFailToConnectPeripheral" is shown in the Xcode's console.

iOS 8.3, the MipDeviceDisconnected:error: is called instead of MipDeviceFailedToConnect:error: in step 5 above, and not "YMSCBCentralManager didFailToConnectPeripheral" found in the Xcode's console, and the MiP robot can be scanned and connected again after step 5.

Thanks

**Comment by ffchan** [comment]
Problem solved on commit 98b119e64da4073ad946963fcfe4ed9bcaf7c7f6.
Please try again.

**Comment by samyusk** [comment]
Have checked the updated framework. It solves the above issue, thanks.
